global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80

providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    swarmModeRefreshSeconds: 15s
    defaultRule: 'Host(`{{ index .Labels "router.hostname" }}`){{ index .Labels "router.pathPrefix" | empty | ternary "" ( list " && PathPrefix(`/" (index .Labels "router.pathPrefix" | trimPrefix "/") "`)" | join "" )}}'

api:
  insecure: true

log:
  level: INFO

accessLog:
  format: clf
